// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Live2dConfig: typeof import('./src/components/Live2dConfig.vue')['default']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NSpace: typeof import('naive-ui')['NSpace']
  }
}
